const positiveThoughts = [
  "You're capable of amazing things!",
  "Every day is a chance to learn something new.",
  "Your positive attitude will lead to great outcomes!",
  "Believe in yourself and your abilities.",
  "Just one small positive thought in the morning can change your whole day",
  "Your attitude is critical to success",
  "If you're going through hell, keep going",
  "Winners never quit, and quitters never win",
  "Doubt kills more dreams than failure ever will",
  "If you want the rainbow, you have to put up with the rain",
  "Those who say it can't be done are usually interrupted by others doing it",
  "Optimism is the faith that leads to achievement",
  "If you're going through hell, keep going",
  "Our greatest weakness lies in giving up",
  "All our dreams can come true, if we have the courage to pursue them",
  "The future belongs to those who believe in the beauty of their dreams",
  "Winners never quit, and quitters never win",
  "Doubt kills more dreams than failure ever will",
  "The superior man is modest in his speech, but exceeds in his actions.",
  "Optimism is the faith that leads to achievement",
  "Our greatest weakness lies in giving up",
  "All our dreams can come true, if we have the courage to pursue them",
  "The future belongs to those who believe in the beauty of their dreams",
  "Winners never quit, and quitters never win",
  "Doubt kills more dreams than failure ever will",
  "If something is important enough, even if the odds are against you, you should still do it.",
  "The only way to do great work is to love what you do.",

"I think it is possible for ordinary people to choose to be extraordinary.",
"When something is important enough, you do it even if the odds are not in your favor.",
"Some people don't like change, but you need to embrace change if the alternative is disaster.",
"Your beliefs become your thoughts. Your thoughts become your words. Your words become your actions. Your actions become your habits. Your habits become your values. Your values become your destiny.",
"All people are the same; only their habits differ.",
"Attack the evil that is within yourself, rather than attacking the evil that is in others.",
"By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.",
"Consideration for others is the basis of a good life, a good society.",
"Education breeds confidence. Confidence breeds hope. Hope breeds peace.",
"Everything has beauty, but not everyone sees it.",
"Give a bowl of rice to a man and you will feed him for a day. Teach him how to grow his own rice and you will save his life.",
"He who conquers himself is the mightiest warrior.",
"He who knows all the answers has not been asked all the questions.",
"How can you love people without encouraging them? And how can you be loyal to people without educating them.",
"I followed my heart without breaking any rules.",
"If a craftsman wants to do good work, he must first sharpen his tools.",
"If either wealth or poverty are come by honesty, there is no shame.",
"If I am walking with two people, both will be my teachers.",
"If you look into your own heart, and you find nothing wrong there, what is there to worry about? What is there to fear?",
"If you make a mistake and do not correct it, this is called a mistake.",
"If your desire is for good, the people will be good.",
"Ignorance is the night of the mind, but a night without moon or star.",
"Imagination is more important than knowledge.",
"It does not matter how slowly you go as long as you do not stop.",
"Learning without thinking is useless. Thinking without learning is dangerous.",
"Life is really simple, but we insist on making it complicated.",
"Music produces a kind of pleasure which human nature cannot do without.",
"Only the wisest and stupidest of men never change.",
"Respect yourself and others will respect you.",
"Signs and symbols rule the world, not words nor laws.",
"Silence is a true friend who never betrays.",

];

function generateThought() {
  const randomIndex = Math.floor(Math.random() * positiveThoughts.length);
  const thought = positiveThoughts[randomIndex];
  document.getElementById('thought').innerText = thought;
}

document.getElementById('generate').addEventListener('click', generateThought);
